# docker compose up -w
services:
  # exec into the container
  # docker compose exec -it go sh
  go:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /app/
    tty: true
